const mongoose = require("mongoose");

const productSchema = new mongoose.Schema({
    brand:{
        type:String,
        required:true,
        index:true
    },
    model:{
        type:String,
        required:true,
        unique:true,
        index:true
    },
    category:{
        type:mongoose.Types.ObjectId,
        ref:"category",
        required:true
    },
    specification:{
        type:String,
        required:true
    },
    images:[{
        url:{
            type:String,
            required:true
        }    
    }],
    listed:{
        type:Boolean,
        default:true
    },
    product_offer:{
        type:Number,
        default:0
    },
    createdOn:{
        type:Date,
        default:Date.now
    },
    variants:[{
            type:mongoose.Types.ObjectId,
            ref:"variant"
    }],
    sales:{
        type:Number,
        default:0
    },
    reviews:[{
        user_id:{
            type:mongoose.Types.ObjectId,
            required:true,
            ref:"user"
        },
        rating:{
            type:Number,
            required:true
        },
        message:{
            type:String,
            required:true
        },
        createdAt:{
            type:Date,
            default:Date.now
        }
    }]
})

module.exports = mongoose.model("product",productSchema)